travis:
  secure:
    BINSTAR_TOKEN: HCLJjJHTiWmTW43oKvE4UfJjyZOKxce0dsV7uN3wnmMA9GIh1UNP0wM6odETwh5UcvuFxSR9XNKo3ZPstjb5zOUSfK0eHoLSJlZ/C3YVzY2Cpsyjqktac6mK2zPMI8PibcnWY0lMEuzCS8R0lP6hSwkmbbVnOTlF1Ybz4dq7w5VzUCE86i9BQEVZVLlNZPqGBeKlnVpT/Jz9uEpUZUjIF+P3yEykv9El3pLp7Z2iG2Ujp0HTM67wVTB22LZzJdNxQ6/xSTWnMltwoQ2bIUgk9GE4geq055iIzGaGe2tbdjS4vZ9lLCz2QDF4nsWVWa5NnP5cBMRXSg5Sl1MqXF2Nv2zuybnVBTH/KOsyhm4cfnx1MoLq7SR2n8ZVVcrIH2e7itBD9EyiYFSEC7Hd2oiTa+zfKB9/MrRlsaWlD3O25UYUf6wcA8o8K4o9FICYBeCjiqWX82Hph9/qhf7lgPTshle2WBFBPE+K9M7Zjqb2yU1sZnDTbQPJ+kcb7QVwXO7vbHHSpQcbLRNfIfYYBzvl3ODcp7oUaewBmOXvsM424ub4JxwDiYVwmwFNt4OiNXAI9g91M5bOEK04gGOeO7SWDaKeyrC1eWXrk8dyPe3pG/7H4dqYppGZ28rmd/avJq2A5OovDO6Gds+tfhvTCRCjTQFsfBAehKFRIwAYNRk8b94=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
