appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OZtI+xm56WV6NKbsSrLOsE5eqNg4KIBjgK/eKYx92dNkHKhdz9/7zybW/WR8TmwhuS0ekxsbdIfbCfUJ+Xvg8+A9FHmOmkDtXDkS1bzbF0Y2Dmc5w/qFfpUSCexXJce9pLyiUvI63vj0pRxFJEKsFzxbzRyeQh2loQFREzyX56uUWxowHiXBTg84lEL80vYmZFmYlUEqUmqjHgmTyF5nERqmeNVabCQQLXi1SySCkDbo5eQ2pKX5ULtsUTYfdDJONsEKlPXUuDOq68pb7f1uW+6SfagkaZfif2LTDXkBPY2kEiJN8mbV0Bb5C4i42W0BS+z78c9jdm0fCvQHv7NNeBdH9aKk868tum88NZAD7JMnQiv0HYsHBHh2/9XwVJakl1PZW7njwA7kGk9tbR0N0I5u9gsAa30C7ZCY0A/H+qjjfsXOYQs6sxpxuOKW9CxGUn5jbjLs7lf+eXEElxZk2+rWlf/nBFCHwdFeTIYDbL45l32WaRQkkOOdJAouZ2dRUMr41WToiaW1CLz1+bD5TDBhPpgHVdlYk41TYeemw6N+y7imflVQgoFKF3DeL3xng+yrbyEr7rjaBiH9OA4jOPVuGZhkNSYdiSRyrAYGui7YzZNgpXQdjRRJEFFs3yCMLG/kO+cqozFQ8XWUg8x7fxaetShuoEmvNm6GD9S/2C4=}
bot:
  automerge: true
